PROGS_MUTEX_CHASER_OBJS := mutex_chaser.o
PROGS_MUTEX_CHASER_OBJS := $(PROGS_MUTEX_CHASER_OBJS:%=$(TDIR)/mutex_chaser/%)
ALL_OBJS += $(PROGS_MUTEX_CHASER_OBJS)

$(TDIR)/bin/mutex_chaser : $(TSTART) $(PROGS_MUTEX_CHASER_OBJS) $(TLIBC)

